repos:
  - repo: local
    hooks:
      - id: rust-fmt
        name: rust fmt
        entry: just fmt-check
        language: system
        pass_filenames: false
      - id: rust-clippy
        name: rust clippy
        entry: just clippy
        language: system
        pass_filenames: false
